
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build/Test
      run: |
        npm ci
        npm run lint
        npm run build
        npm run test:main
        npm run test:esm
        npm run test:esnext

    - name: Prepare ESLint Report
      run: sed -i 's+/home/runner/work/sunday-js/sunday-js+/github/workspace+g' reports/lint.json

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
