name: Publish Release

on:
  push:
    tags: ['*.*.*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.10

    - name: Check Version Format in Tag
      id: version
      uses: nowsprinting/check-version-format-action@v3

    - name: Install Packages
      run: bun install --frozen-lockfile

    - name: Stamp Package Version
      run: bun pm pkg set version=${{ github.ref_name }}

    - name: Publish Package
      run: bun publish
      env:
        NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build Documentation
      run: bun run docs -- --out docs/${{ github.ref_name }}

    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        clean: false
        folder: docs

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: 🚀 ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
        prerelease: ${{ steps.version.outputs.is_stable != 'true' }}
        draft: false
